### ISSUE TITLE
Issues Run Command CI/CD in windows 10 

### ISSUE THREAD

**Issue by LongND-NTQ** [ibrahim-mubarak/define-env#12]
![image](https://github.com/ibrahim-mubarak/define-env/assets/131839775/17df2548-3506-4ca1-a6ce-25550089bc78)
 I have been error in windows 10,  in macOS is good

**Comment by ibrahim-mubarak** [comment]
The command mentioned in the readme is for Unix based OS

I do not have a windows system to test this out,
but you can probably try this and see if it works for you

```powershell
if (doppler secrets download --format=env --no-file | define_env  -f - -match ".*") { flutter build appbundle --release }
```
